Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian12"
  config.vm.box_version = "4.3.12"

  config.vm.define "app" do |app|
  #app.vm.synced_folder "vagrant", "/registry"
  app.vm.network "forwarded_port", guest: 1323, host: 1323
  app.vm.provision "shell", inline: <<-SHELL
      curl -fsSL https://get.docker.com -o get-docker.sh
      sudo sh ./get-docker.sh
      sudo usermod -aG docker vagrant
  SHELL
  end
end
